### ISSUE TITLE
SQL FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#100]
```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:972)
       at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
       at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
       at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:229)
       at org.gnucash.android.db.adapter.AccountsDbAdapter.addRecord(AccountsDbAdapter.java:161)
       at org.gnucash.android.ui.account.AccountFormFragment.saveAccount(AccountFormFragment.java:771)
       at org.gnucash.android.ui.account.AccountFormFragment.onOptionsItemSelected(AccountFormFragment.java:579)
       at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3122)
       at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3226)
       at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
       at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
       at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
       at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
       at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
       at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
       at android.view.View.performClick(View.java:7792)
       at android.widget.TextView.performClick(TextView.java:16112)
       at android.view.View.performClickInternal(View.java:7769)
       at android.view.View.access$3800(View.java:910)
       at android.view.View$PerformClick.run(View.java:30218)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by Kaligula0** [comment]
When that happens?
