### ISSUE TITLE
Accounts list missing record

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#101]
```
Fatal Exception: java.lang.IllegalArgumentException: Record with GUID 978...196 does not exist in the db
       at org.gnucash.android.db.adapter.DatabaseAdapter.getAttribute(DatabaseAdapter.java:782)
       at org.gnucash.android.db.adapter.DatabaseAdapter.getAttribute(DatabaseAdapter.java:755)
       at org.gnucash.android.db.adapter.AccountsDbAdapter.isPlaceholderAccount(AccountsDbAdapter.java:1156)
       at org.gnucash.android.ui.account.AccountsListFragment$AccountRecyclerAdapter.onBindViewHolderCursor(AccountsListFragment.java:521)
       at org.gnucash.android.ui.account.AccountsListFragment$AccountRecyclerAdapter.onBindViewHolderCursor(AccountsListFragment.java:483)
       at org.gnucash.android.ui.util.CursorRecyclerAdapter.onBindViewHolder(CursorRecyclerAdapter.java:101)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1273)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
       at android.view.View.layout(View.java:23030)
       at android.view.ViewGroup.layout(ViewGroup.java:6455)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3580)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3038)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2020)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8410)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:974)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:959)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7723)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by Kaligula0** [comment]
When that happens?
