### ISSUE TITLE
Unable to start receiver org.gnucash.android.receivers.TransactionRecorder

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#114]
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver org.gnucash.android.receivers.TransactionRecorder: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
       at android.app.ActivityThread.-wrap17()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
Caused by java.lang.NullPointerException:
       at org.gnucash.android.model.Transaction.setDescription(Transaction.kt:275)
       at org.gnucash.android.model.Transaction.<init>(Transaction.kt:86)
       at org.gnucash.android.receivers.TransactionRecorder.onReceive(TransactionRecorder.java:70)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by pnemonic78** [comment]
```
Caused by java.lang.NullPointerException: Parameter specified as non-null is null: method org.gnucash.android.model.Account.<init>, parameter name
       at org.gnucash.android.model.Account.<init>(:2)
       at org.gnucash.android.receivers.AccountCreator.onReceive(AccountCreator.java:50)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
