### ISSUE TITLE
Failing Instrumentation Test: PieChartReportTest.testSelectingValue

### ISSUE THREAD

**Issue by djbrown** [GnuCash-Pocket/gnucash-android#13]
There is one failing test in the nightly test suite (#7).
Test: `org.gnucash.android.test.ui.PieChartReportTest.testSelectingValue`
Error message: `Instrumentation run failed due to 'Process crashed.'`
Flavor: `betaDebugAndroidTest`

<details>
  <summary>Device Log</summary>

Timestamp | Level | Tag | Message
-- | -- | -- | --
10-16 20:22:00.003 | debug | TransactionsDbAdapter | 2 splits added
10-16 20:22:00.004 | debug | TransactionsDbAdapter | 0 splits deleted
10-16 20:22:00.055 | verbose | AccountsDbAdapter | Fetching all accounts from db where null order by full_name ASC
10-16 20:22:00.358 | warn | SQLiteConnectionPool | A SQLiteConnection object for database '/data/user/0/org.gnucash.android/databases/cad76b596dab453599736d7ff3290644' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 20:22:00.358 | warn | SQLiteConnectionPool | A SQLiteConnection object for database '/data/user/0/org.gnucash.android/databases/68cee89dfcb04f558f3b73fd7b6a3170' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 20:22:00.365 | warn | SQLiteConnectionPool | A SQLiteConnection object for database '/data/user/0/org.gnucash.android/databases/e6e9d8f87ef143dbacf439a5984017fe' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 20:22:00.386 | debug | AndroidRuntime | Shutting down VM
10-16 20:22:00.386 | debug | AndroidRuntime | --------- beginning of crash
10-16 20:22:00.388 | error | AndroidRuntime | FATAL EXCEPTION: main
10-16 20:22:00.388 | error | AndroidRuntime | Process: org.gnucash.android, PID: 2965
10-16 20:22:00.388 | error | AndroidRuntime | java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
10-16 20:22:00.388 | error | AndroidRuntime | at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:239)
10-16 20:22:00.388 | error | AndroidRuntime | at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:114)
10-16 20:22:00.388 | error | AndroidRuntime | at android.view.View.draw(View.java:19192)
10-16 20:22:00.448 | error | THREAD_STATE | Thread[MultiThreadedHttpConnectionManager cleanup,5,main]
10-16 20:22:00.448 | error | THREAD_STATE | java.lang.Object.wait(Native Method)
10-16 20:22:00.448 | error | THREAD_STATE | java.lang.Object.wait(Object.java:422)
10-16 20:22:00.448 | error | THREAD_STATE | java.l
10-16 20:22:00.448 | error | MonitoringInstr | Dying now...
10-16 20:22:00.465 | info | Process | Sending signal. PID: 2965 SIG: 9
</details>

<details>
  <summary>Stacktrace</summary>

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:239)
    at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:114)
    at android.view.View.draw(View.java:19192)
    at android.view.View.updateDisplayListIfDirty(View.java:18142)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
    at android.view.View.updateDisplayListIfDirty(View.java:18101)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
    at android.view.Choreographer.doCallbacks(Choreographer.java:723)
    at android.view.Choreographer.doFrame(Choreographer.java:658)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
</details>

**Comment by djbrown** [comment]
It could be either a functional problem (ArrayIndexOutOfBoundsException),
or it could be that the device chrashes prematurely from another reason.

Next step would be to reproduce this error locally.
I can only use a real device, since HAXM is not installable on my machine.

**Comment by djbrown** [comment]
See Nightly Build 1 -> [Artifacts](https://github.com/GnuCash-Pocket/gnucash-android/actions/runs/3261291532#artifacts) -> "Spoon Test Report 1.1"

**Comment by arozaqf** [comment]
@djbrown i can recreate it first forceclosed, select report, pie chart, select period 1 of november and second 31 october, and lastly done,

**Comment by djbrown** [comment]
@arozaqf do you mean you can recreate the error? or you can recreate the test and it works on your phone?

**Comment by arozaqf** [comment]
@djbrown i recreate the error...

**Comment by djbrown** [comment]
Not failing on recent device see 6e11717 - [Instrumentation Test Report](https://github.com/GnuCash-Pocket/gnucash-android/actions/runs/5138634454/jobs/9248263990)
