### ISSUE TITLE
No active book

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#167]
```
 Caused by org.gnucash.android.db.adapter.BooksDbAdapter$NoActiveBookFoundException: There is no active book in the app.
This should NEVER happen - fix your bugs!
UID, created, source

       at org.gnucash.android.db.adapter.BooksDbAdapter.getActiveBookUID(BooksDbAdapter.java:178)
       at org.gnucash.android.app.GnuCashApplication.initializeDatabaseAdapters(GnuCashApplication.java:165)
       at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:139)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by pnemonic78** [comment]
```
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gnucash.pocket.pnemonic.devel/org.gnucash.android.ui.account.AccountsActivity}: org.gnucash.android.db.adapter.BooksDbAdapter$NoActiveBookFoundException: There is no active book in the app.
                 This should NEVER happen - fix your bugs!
                 UID, created, source
                 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by pnemonic78** [comment]
To reproduce:
0. Attach debugger and breakpoint where import default accounts
1. New install
2. First Run Wizard - Done
3. Stop process
