### ISSUE TITLE
Event Recurrence

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#172]
```
 Fatal Exception: java.lang.IllegalStateException: freq=6
       at com.codetroopers.betterpickers.recurrencepicker.RecurrencePickerDialogFragment.copyEventRecurrenceToModel(RecurrencePickerDialogFragment.java:513)
       at com.codetroopers.betterpickers.recurrencepicker.RecurrencePickerDialogFragment.onCreateView(RecurrencePickerDialogFragment.java:696)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
       at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by pnemonic78** [comment]
```
          Fatal Exception: com.codetroopers.betterpickers.recurrencepicker.EventRecurrence$InvalidFormatException: Invalid BYDAY value: LU
       at com.codetroopers.betterpickers.recurrencepicker.EventRecurrence$ParseByDay.parseWday(EventRecurrence.java:878)
       at com.codetroopers.betterpickers.recurrencepicker.EventRecurrence$ParseByDay.parsePart(EventRecurrence.java:842)
       at com.codetroopers.betterpickers.recurrencepicker.EventRecurrence.parse(EventRecurrence.java:619)
       at org.gnucash.android.ui.transaction.TransactionFormFragment.onRecurrenceSet(TransactionFormFragment.java:1153)
       at org.gnucash.android.ui.transaction.TransactionFormFragment.initializeViewsWithTransaction(TransactionFormFragment.java:518)
       at org.gnucash.android.ui.transaction.TransactionFormFragment.onViewCreated(TransactionFormFragment.java:289)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
       at android.app.Activity.performStart(Activity.java:8968)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```
