### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#186]
```
          Caused by java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 101952 free bytes and 99KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
       at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:88)
       at java.lang.StringBuilder.<init>(StringBuilder.java:103)
       at java.util.UUID.toString(UUID.java:522)
       at org.gnucash.android.model.BaseModel$Companion.generateUID(BaseModel.kt:104)
       at org.gnucash.android.model.Split.<init>(Split.kt:114)
       at org.gnucash.android.model.Transaction.<init>(Transaction.kt:103)
       at org.gnucash.android.service.ScheduledActionService.executeTransactions(ScheduledActionService.java:250)
       at org.gnucash.android.service.ScheduledActionService.executeScheduledEvent(ScheduledActionService.java:137)
       at org.gnucash.android.service.ScheduledActionService.processScheduledActions(ScheduledActionService.java:122)
       at org.gnucash.android.service.ScheduledActionService.onHandleWork(ScheduledActionService.java:89)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by pnemonic78** [comment]
> @pnemonic78 is this closed by #187?

I haven't received new complaints yet.
