### ISSUE TITLE
Failed to generate GnuCash transactions CSV-divide by zero

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#98]
```
Non-fatal Exception: org.gnucash.android.export.Exporter$ExporterException: Failed to generate GnuCash transactions CSV-divide by zero
       at org.gnucash.android.export.csv.CsvTransactionsExporter.generateExport(CsvTransactionsExporter.java:177)
       at org.gnucash.android.export.csv.CsvTransactionsExporter.generateExport(CsvTransactionsExporter.java:86)
       at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:136)
       at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:89)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.lang.ArithmeticException: divide by zero
       at java.math.BigDecimal.divideAndRound(BigDecimal.java:4695)
       at java.math.BigDecimal.divide(BigDecimal.java:5768)
       at java.math.BigDecimal.divide(BigDecimal.java:1659)
       at java.math.BigDecimal.divide(BigDecimal.java:1689)
       at org.gnucash.android.model.Money.div(Money.kt:337)
       at org.gnucash.android.model.Money.div(Money.kt:355)
       at org.gnucash.android.export.csv.CsvTransactionsExporter.writeSplitsToCsv(CsvTransactionsExporter.java:143)
       at org.gnucash.android.export.csv.CsvTransactionsExporter.generateExport(CsvTransactionsExporter.java:171)
       at org.gnucash.android.export.csv.CsvTransactionsExporter.generateExport(CsvTransactionsExporter.java:86)
       at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:136)
       at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:89)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Kaligula0** [comment]
When that happens?

**Comment by BaumiCoder** [comment]
I tested the export with version 2.5.3 (Update from the 9th January 2025), which should contain the changes form #196. I opened a database from gnucash desktop version and made an export for about the last 2 weeks, which contains some transactions:

- CSV: Contains all transactions of the database.
- QIF: Error message "Error when exporting the QIF file"

If the problems are not reproducible at your side after the changes, you can tell me which additional information (logs or something like this) I can provide to help.

**Comment by pnemonic78** [comment]
@BaumiCoder 

1. Export checks the modification date of transactions - so a newly imported book has all modifications set to that day.
2. QIF export - can you send me the problematic gnucash file?

**Comment by BaumiCoder** [comment]
1. Okay, this is no suitable behavior. Will be addressed with #252, right?
2. The problematic gnucash file contains my real financial data. Therefore, I don't want to share this file. I try to reproduce a similar file (XML format, German settings), but I am not able to create another file with this error. Can I somehow provide information about the reason without sharing the gnucash file? Are there any logs about such errors?

**Comment by pnemonic78** [comment]
Can send debug logs from device.
Not sure how your Android is setup.

**Comment by BaumiCoder** [comment]
I was able to export some logs from a reproduction with [SysLog](https://f-droid.org/de/packages/com.tortel.syslog/) after giving permissions with adb. Gnucash produces some lines in the logcat.log (see [logcat_gnucash.log](https://github.com/user-attachments/files/18656015/logcat_gnucash.log)). The most suspect entry seems to be this one:
```
02-04 11:42:44.840 E/ExportAsyncTask(17559): org.gnucash.android.export.Exporter$ExporterException: Failed to generate export with parameters: Export all transactions created since 2025-01-01 12:32:31.917 UTC as QIF to SHARING - split quantity has illegal denominator: 100000000
```
