### ISSUE TITLE
What color format starts with "g"?

### ISSUE THREAD

**Issue by pnemonic78** [GnuCash-Pocket/gnucash-android#99]
```
Non-fatal Exception: java.lang.NumberFormatException: For input string: "g(2250"
       at java.lang.Long.parseLong(Long.java:594)
       at android.graphics.Color.parseColor(Color.java:1386)
       at org.gnucash.android.model.Account.setColor(Account.kt:229)
       at org.gnucash.android.importer.GncXmlHandler.endElement(GncXmlHandler.java:547)
       at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:167)
       at org.apache.harmony.xml.ExpatParser.appendBytes(ExpatParser.java)
       at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:526)
       at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:487)
       at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:324)
       at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:287)
       at org.gnucash.android.importer.GncXmlImporter.parse(GncXmlImporter.java:70)
       at org.gnucash.android.importer.ImportAsyncTask.doInBackground(ImportAsyncTask.java:84)
       at org.gnucash.android.importer.ImportAsyncTask.doInBackground(ImportAsyncTask.java:44)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by Kaligula0** [comment]
What is that and when that happens?

**Comment by djbrown** [comment]
@pnemonic78 could you please explain how this error came up? 😅
I've looked at the PR #103 and think i've understood the changes, but not the original problem.
I see there are tests for the more robust color parsing, but how would one test this original problem?

**Comment by pnemonic78** [comment]
the stack trace above is from crashlytics from real users

**Comment by djbrown** [comment]
yes, so you don't know either how the user got there?
